### PR TITLE
Refactor gentests to compile with latest openssl, resolve floating point issues

### PR DESCRIPTION
**Pull request by anp**
Followup to https://github.com/vislyhq/stretch/pull/20.

I wanted to re-generate the tests myself locally and couldn't due to a mismatch with openssl. This turned into a bit of a rabbit hole, but nearly everything seems to be good now, with the exception of one test. I'll investigate that case and follow up.

To make the significant changes to the generated tests easier to review, I have two commits here: one to split up the original generated test code into separate files, and the second containing the changes to the generator I'm proposing and the associated changes to generated files. I believe the diffs on the generated tests should only be due to changed the way numeric literals are printed, which resolved a dozen tests that had started failing after the selenium -> WebDriver switch.

@emilsjolander do you have a sec to review? I think this is ready enough for feedback while I figure out the one ignored test.

### CODE REVIEW

**Comment by emilsjolander** [comment]
This looks great! I’ll have a look first thing tomorrow :)

**Comment by emilsjolander** [comment]
Just had time to look closer. This is awesome!! Thanks so much for doing this. Do you have idea why `flex_basis_smaller_than_content_column` is failing after the refactor? Happy to help look into why.

**Comment by anp** [comment]
Hah! Now that I've had time to dig in, the test failure is pretty simple:

https://github.com/vislyhq/stretch/pull/21/commits/89b8f27c5dd95928e190f1d42fd1884406756968#diff-d6f4bae2a49069bd4f8161a30ad4c1f1L32

vs.

https://github.com/vislyhq/stretch/pull/21/commits/89b8f27c5dd95928e190f1d42fd1884406756968#diff-d6f4bae2a49069bd4f8161a30ad4c1f1R31

What's more curious is why the code generation is producing that change. I'll dig in more.

**Comment by anp** [comment]
Hm, interesting. Opening the test fixture in Chrome and Firefox shows me a div which has been laid out with a height of 100px:

Screenshot from 2019-03-28 18-38-19

Screenshot from 2019-03-28 18-39-27

which is the [literal written by the new test generator](https://github.com/vislyhq/stretch/commit/89b8f27c5dd95928e190f1d42fd1884406756968#diff-d6f4bae2a49069bd4f8161a30ad4c1f1R31). However stretch is reporting 50px, same as the previous test had:

```
---- generated::flex_basis_smaller_than_content_column::flex_basis_smaller_than_content_column stdout ----
thread 'generated::flex_basis_smaller_than_content_column::flex_basis_smaller_than_content_column' panicked at 'assertion failed: `(left == right)`
  left: `50.0`,
 right: `100.0`', tests/generated/flex_basis_smaller_than_content_column.rs:31:5
```

I'm on Linux and don't have handy access to another computer just now. Could this test difference be due to platform differences?

Maybe browsers changed their behavior since the previous tests were generated and now?

**Comment by emilsjolander** [comment]
Good catch! I had an outdated chrome version (v71), updating and re-generating the tests I get the same output as you and yes it seems like Chrome has fixed something in their flexbox algorithm which we need to fix as well 👍 This has nothing to do with this PR so I suggest we merge this and then i'll look at fixing this test asap.

**Comment by emilsjolander** [comment]
Let me know if you are ready to merge!

**Comment by emilsjolander** [comment]
@anp If you rebase now all the tests should be passing!

**Comment by emilsjolander** [comment]
@anp Let me know if you want me to rebase and merge this myself. I'm doing a larger redesign of the API to accommodate some new features and would love to have this in before I start making drastic changes 👍

**Comment by anp** [comment]
Happy for you to rebase, i probably won’t be able to until tomorrow sometime.

**Comment by emilsjolander** [comment]
Ok that's fine! I'm out of office for the next 24 hours :) If you have the chance to rebase, perfect! otherwise i'll rebase and merge when i'm back, no worries :) Huge thanks for the contribution either way!!

**Comment by emilsjolander** [comment]
Merged! Thanks for the contribution!

**Pull request merged**
