### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by adamnemecek**
This supersedes https://github.com/vislyhq/stretch/pull/64

### CODE REVIEW

**Comment by adamnemecek** [comment]
I think it might also be a good idea for the project to have a prelude. I can add it.

**Comment by emilsjolander** [comment]
Looks good! Happy to merge once iOS tests pass

**Comment by adamnemecek** [comment]
It seems like they are failing because a macOS plan is not setup. Is that something I have to do?

**Comment by emilsjolander** [comment]
Oh oops. We stopped using circleCI internally so I canceled our macOS plan forgetting it was used here lol. I'll get it sorted

**Comment by adamnemecek** [comment]
Thx.

**Comment by adamnemecek** [comment]
Can you merge this? I'd like to add some more things but I dont want to add them to this PR.

**Comment by emilsjolander** [comment]
@adamnemecek done, thanks!

**Comment by adamnemecek** [comment]
Thx

**Pull request merged**
